"""Regression coverage for server/model copy emitted under the OM brand."""

from pathlib import Path
from urllib.parse import parse_qs, urlparse

from core.auth import AuthManager
from routes.email_helpers import _friendly_email_auth_error
from routes.mcp_routes import _oauth_authorize_page
from routes.shell_routes import _package_pip_update_status
from src.agent_loop import (
    _minimal_odysseus_doc_messages,
    _minimal_odysseus_general_messages,
    _minimal_odysseus_notes_messages,
)
from src.branding import get_brand_config
from src.reminder_personas import PERSONAS
from src.tool_schema_catalog import FUNCTION_TOOL_SCHEMAS
from src.visual_report import generate_visual_report


ROOT = Path(__file__).resolve().parents[1]
GREEK_PERSONA_TERMS = ("king of ithaca", "homer", "odyssey", "telemachus", "penelope")


def test_default_model_prompts_use_central_om_persona_without_greek_roleplay():
    configured = get_brand_config().copy_text.default_persona
    prompts = [
        _minimal_odysseus_doc_messages([], None, stream_create=True)[0]["content"],
        _minimal_odysseus_doc_messages([], None, stream_create=False)[0]["content"],
        _minimal_odysseus_notes_messages([])[0]["content"],
        _minimal_odysseus_general_messages([])[0]["content"],
        PERSONAS["odysseus"],  # persisted compatibility ID
    ]

    for prompt in prompts:
        assert configured in prompt
        lowered = prompt.lower()
        assert "you are odysseus" not in lowered
        assert all(term not in lowered for term in GREEK_PERSONA_TERMS)


def test_generated_research_report_carries_om_brand():
    rendered = generate_visual_report(
        "How should we proceed?",
        "# Delivery Plan\n\nUse a measured, verifiable rollout.",
    )

    assert "OM Automate &mdash; Deep Research Report" in rendered
    assert "Generated by OM Automate Deep Research" in rendered
    assert "Generated by Odysseus" not in rendered


def test_totp_issuer_and_oauth_page_use_om_brand(tmp_path):
    manager = AuthManager(str(tmp_path / "auth.json"))
    uri = manager.totp_get_provisioning_uri("alice", "JBSWY3DPEHPK3PXP")
    issuer = parse_qs(urlparse(uri).query)["issuer"]

    assert issuer == ["OM Automate"]
    page = _oauth_authorize_page(
        "https://accounts.example/authorize",
        "server-1",
        "localhost:7000",
    )
    assert "Authorize — OM Automate" in page
    assert "Authorize — Odysseus" not in page


def test_user_facing_backend_errors_use_om_brand():
    outlook_error = _friendly_email_auth_error(
        "imap",
        "outlook.office365.com",
        "Basic authentication is disabled",
    )
    package_status = _package_pip_update_status({"kind": "system"})

    assert "OM Automate does not support" in outlook_error
    assert "outside OM Automate" in package_status.note


def test_notification_and_model_endpoint_copy_has_no_legacy_product_name():
    expected = {
        "routes/auth_routes.py": (
            "OM Automate connectivity test",
            "Connectivity test from OM Automate",
        ),
        "routes/email_pollers.py": ("Open in OM Automate",),
        "routes/model_routes.py": ("That is OM Automate, not a model server",),
        "services/hwfit/hardware.py": ("inside the OM Automate container",),
    }
    forbidden = (
        "Odysseus connectivity test",
        "Connectivity test from Odysseus",
        "Open in Odysseus",
        "That is Odysseus, not a model server",
        "inside the Odysseus container",
    )

    for relative_path, required_strings in expected.items():
        source = (ROOT / relative_path).read_text(encoding="utf-8")
        assert all(value in source for value in required_strings)
        assert all(value not in source for value in forbidden)


def test_new_reminder_and_calendar_writers_use_om_but_keep_legacy_readers():
    note_source = (ROOT / "routes/note_routes.py").read_text(encoding="utf-8")
    email_source = (ROOT / "routes/email_routes.py").read_text(encoding="utf-8")
    calendar_source = (ROOT / "routes/calendar_routes.py").read_text(encoding="utf-8")
    caldav_source = (ROOT / "src/caldav_writeback.py").read_text(encoding="utf-8")

    assert 'f"Reminder ({_BRAND.product_name}): {_t}"' in note_source
    assert 'msg["Subject"] = f"Reminder (Odysseus)' not in note_source
    assert '_REMINDER_SUBJECT_PREFIX' in email_source
    assert '_LEGACY_REMINDER_SUBJECT_PREFIX = "Reminder (Odysseus):"' in email_source
    assert 'f"-//{get_brand_config().product_name}//Calendar//EN"' in calendar_source
    assert 'f"-//{get_brand_config().product_name}//CalDAV write-back//EN"' in caldav_source


def test_model_tool_catalog_and_cookbook_guidance_use_om_brand():
    app_api = next(
        schema["function"]
        for schema in FUNCTION_TOOL_SCHEMAS
        if schema["function"]["name"] == "app_api"
    )
    assert "OM Automate endpoints" in app_api["description"]
    assert "Odysseus endpoints" not in app_api["description"]

    cookbook_source = (ROOT / "routes/cookbook_routes.py").read_text(encoding="utf-8")
    assert "Add one in OM Automate Cookbook" in cookbook_source
    assert "OM Automate now rewrites MLX repo-id launches" in cookbook_source
    assert "so OM Automate can reach it from this host" in cookbook_source

    helper_source = (ROOT / "routes/cookbook_helpers.py").read_text(encoding="utf-8")
    assert "OM Automate now rewrites MLX repo-id launches" in helper_source
